realiza ajustes para utilizar a engine ao rodar projetos no windows
meliuz-training/lib-showcase-engine pull request #1
Opened 2021-11-14 23:35 UTC by thebestlucc

Fiz algumas alterações nos arquivos relacionados ao _AndroidRunner_ e geração de arquivos da engine quando utilizada no windows.

2021-11-15 14:29 UTC, lizardo requested changes
- A parte dos paths parece OK!
- Os 2 locais que chamam `adb devices` precisa de ajuste pois não funciona com devices que não tenham hifen no nome. Dei uma sugestão que acredito ser universão (Linux/Mac/Win)
- Notei alguns probleminhas de linting, mas depois de ajustar o ponto acima, farei uma outra PR corrigindo eles de forma mais global para o projeto.

2021-11-15 14:29 UTC, lizardo commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/runners/AndroidRunner.js
> +    return device
Poderia testar esse código no Windows, ao invés das linhas acima?

```javascript
return childProcess
    .execSync(`${this._adb} devices`)
    .toString()
    .split('\n')
    .map(s => s.split('\t'))
    .filter(l => l[1] === 'device')
    .map(l => l[0]);
```

Talvez o `.split('\n')` precise ser ajustado no Windows (pois pode estar usando `\r\n` como quebra de linha), mas veja se funciona. Se não, tente ajustar o split():   `.split(isWin: '\r\n' : '\n')`

2021-11-15 14:29 UTC, lizardo commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/utils/Adb.js
> +      devices = String(devicesOutput).match(/[\w|\d]+-\d+/g);
Baseado no mesmo comentário que fiz acima, poderia tentar esse código?

```javascript
devices = childProcess
    .execSync(`${ADB_PATH} devices`)
    .toString()
    .split('\n')
    .map(s => s.split('\t'))
    .filter(l => l[1] === 'device')
    .map(l => l[0]);
```

2021-11-16 17:03 UTC, thebestlucc commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/utils/Adb.js
> +      devices = String(devicesOutput).match(/[\w|\d]+-\d+/g);
@lizardo testei esse código que vc sugeriu e funcionou de boas no windows, não precisou ajustar o `\n`

2021-11-16 17:50 UTC, lizardo requested changes

2021-11-16 17:50 UTC, lizardo commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/runners/AndroidRunner.js
> +    const outputString = isWin ? `${this._adb} devices ` : `${this._adb} devices | tail -n +2 | cut -sf 1`;
Faltou trocar aqui pelo código que gera a lista de devices (é o mesmo que você colocou no arquivo `internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/utils/Adb.js`).

Além disso, a linha:

```javascript
const outputString = isWin ? `${this._adb} devices ` : `${this._adb} devices | tail -n +2 | cut -sf 1`;
```

Pode virar simplesmente:

```javascript
const outputString = `${this._adb} devices`;
```

Pois o código que propus funciona em qualquer plataforma :wink:

2021-11-16 17:50 UTC, lizardo commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/utils/Adb.js
> +      devices = String(devicesOutput)
Está faltando uma parte do código que faz o split das linhas (o `split('\n')`),  sem ela, não vai funcionar quando tiver mais de um device listado pelo `adb devices`.

Além disso, pode substituir a linha:

```javascript
const outputString = isWin ?`${ADB_PATH} devices ` : `${ADB_PATH} devices | tail -n +2 | cut -sf 1`;
```

Por esta:

```javascript
const outputString = `${ADB_PATH} devices`;
```

Pois o trecho de código usado substitui esses tail + cut das outras plataformas :wink:

2021-11-16 18:16 UTC, thebestlucc commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/utils/Adb.js
> +      devices = String(devicesOutput)
opa, fiz as alterações sugeridas, caso note algo, me sinaliza de novo

2021-11-16 18:16 UTC, thebestlucc commented on internal_folder/@meliuz-training/lib-showcase-engine/tools/engine_cli/src/runners/AndroidRunner.js
> +    const outputString = isWin ? `${this._adb} devices ` : `${this._adb} devices | tail -n +2 | cut -sf 1`;
alterações feitas

2021-11-17 01:05 UTC, lizardo approved these changes

2021-11-17 01:05 UTC, merged